Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/4/2021
Var
// Seção de Declarações das variáveis 
quadrado, numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um numero para se calcular o seu quadrado: ")
leia(numero)
quadrado <- exp(numero,2)
escreval("O quadrado desse numero é ", quadrado)

Fimalgoritmo