Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/4/2021
Var
// Seção de Declarações das variáveis 
celsius, fahrenheit:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a temperatura em graus Celsius: ")
leia (celsius)
fahrenheit <- ((9/5)* Celsius) + 32

escreval("A temperatura em Fahrenheit é ", fahrenheit)

Fimalgoritmo