Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/4/2021
Var
// Seção de Declarações das variáveis 
 polegadas: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a quantidade de chuva em polegadas: ")
leia(polegadas)
escreval("A quantidade de chuva em milímetros é de: ", polegadas*25.4, " mm")

Fimalgoritmo